# -*- coding: utf-8 -*-
"""__init__.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mfQfxvaX3TDriRSkAXHFnoYqndAxGFmW
"""

# tokenizer4o/__init__.py
from .tokenizer import Tokenizer4o

__version__ = "1.0.0"
__all__ = ['Tokenizer4o']